apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: earthquake
data:
  POSTGRES_DB: "earthquakedb"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/earthquakedb"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: earthquake
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
